### ISSUE TITLE
Lien vers ton site

### ISSUE THREAD

**Issue by davidmarsprof** [RedDarkS/unseriousgame#1]
Hello, dans le fichier README.md peux-tu mettre le lien vers ton site s'il te plait?

**Comment by RedDarkS** [comment]
Je viens seulement de découvrir votre message, tout le monde ne parlé et moi je m'attendais à un mp discord.
Bon normalement c'est fait.

**Comment by davidmarsprof** [comment]
Pas de stress, c'est le principe de github, pouvoir travailler à plusieurs sur un projet d'où on veut quand chacun veut.
Bon par contre revois tes liens car ton gameplay est pas super logique ;)
